# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test

on:
    push:
        branches: [master]
    pull_request:
        types: [opened, synchronize]
        branches:
            - '**'
jobs:
  build-and-test:
    name: Build and Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Docker setup
      run: docker-compose -f docker-compose-ci.yaml up -d --build
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Run test
      run: |
        yarn install
        yarn lint
        yarn test
